FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
python3 \
python3-pip \
build-essential \
g++ \
libstdc++6 \
nodejs \
npm \
&& rm -rf /var/lib/apt/lists/*


COPY package.json  package-lock.json ./
RUN npm ci

COPY requirements.txt ./
RUN python3 -m venv .venv
RUN .venv/bin/pip install --upgrade pip
RUN .venv/bin/pip install -r requirements.txt

COPY . .
CMD ["node", "server.js"]