FROM node:18-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y \
python3 \
python3-pip \
build-essential \
g++ \
libstdc++6 \
&& rm -rf /var/lib/apt/lists/*

COPY package.json  package-lock.json ./
RUN npm ci

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .
CMD ["node", "server.js"]