[phases.setup]

nixPkgs = ["python311", "nodejs", "python311Packages.numpy", "python311Packages.tensorflow", "python311Packages.pip"]

[phases.install]
cmds = ["npm ci", "pip install -r requirements.txt"]